In [8]:
# 10.1 번
import numpy as np
num_arr = np.array(range(1, 21))
print(num_arr)
print(np.flip(num_arr))
print("num_arr 내의 모든 원소의 합 : %d" % (np.sum(num_arr)))
print(num_arr.reshape(5, 4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
num_arr 내의 모든 원소의 합 : 210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [80]:
# 10.2 번
# 1)
n_arr = np.arange(25).reshape(5, 5)
print(n_arr, "\n")
# 2)
print("첫 원소 : %d" % (n_arr[0, 0]))
print("마지막 원소 : %d" % (n_arr[-1,-1]), "\n")
# 3)
print(n_arr[:2], "\n")
# 4)
print(n_arr[2:], "\n")
# 5)
print(n_arr[:,::2], "\n")
# 6)
print(n_arr[::2, ::2], "\n")
#7)
print(n_arr[:2].reshape(5, 2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

첫 원소 : 0
마지막 원소 : 24 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]] 

[[ 0  2  4]
 [10 12 14]
 [20 22 24]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [78]:
# 10.3번
# 1)
a = np.array(np.random.rand(27).reshape(3, 3, 3))
print(a, "\n")
# 2)
print("a의 원소들 중 최댓값 :", a.max(), "\n")
# 3)
print("a의 원소들 중 최댓값의 위치 :", a.argmax())

[[[0.99446296 0.82924464 0.92022768]
  [0.44467351 0.97531219 0.9536364 ]
  [0.91250687 0.21537116 0.04574824]]

 [[0.4535393  0.75896792 0.22481872]
  [0.05698942 0.51803203 0.83070224]
  [0.37569578 0.42447326 0.28033324]]

 [[0.62539951 0.84011826 0.56883518]
  [0.34217709 0.62456537 0.14205743]
  [0.78931867 0.6045002  0.60771609]]] 

a의 원소들 중 최댓값 : 0.9944629583924333 

a의 원소들 중 최댓값의 위치 : 0


In [79]:
# 10.4번
# 1)
a = np.array([0 for i in range(25)])
a[::2] = 1
a = a.reshape(5, 5)
print(a, "\n")
# 2)
print("행렬의 행 방향 성분의 합 :")
print(a.sum(axis=0))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]] 

행렬의 행 방향 성분의 합 :
[3 2 3 2 3]


In [76]:
# 10.5번
a = np.arange(0, 32).reshape(4, 4, 2).flatten()
print("10번째 원소 : %d\n20번째 원소 : %d" % (a[9], a[19]))

10번째 원소 : 9
20번째 원소 : 19


In [90]:
# 10.6번
x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1, 10) for i in range(100)]
x3 = [i + np.random.randint(1, 50) for i in range(100)]
x4 = [np.random.randint(1, 100) for i in range(100)]

print(np.corrcoef([x1, x2, x3, x4]), '\n')
# 1)
print("x1과 가장 상관관계가 높은 리스트 : x2")
# 2)
print("x1과 가장 상관관계가 낮은 리스트 : x4")

[[ 1.          0.99667792  0.88705506 -0.1175656 ]
 [ 0.99667792  1.          0.88557133 -0.10638148]
 [ 0.88705506  0.88557133  1.         -0.10866422]
 [-0.1175656  -0.10638148 -0.10866422  1.        ]] 

x1과 가장 상관관계가 높은 리스트 : x2
x1과 가장 상관관계가 낮은 리스트 : x4
